version: "3.9"
services:
  mongo-database:
    image: mongo:4.2.23
    volumes:
      - /Users/eloigabal/Desktop/Distributed Computing/2425/examples/docker_data/mongo_data:/data/db
  express:
    image: mongodb/atlas:latest
    #image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-database
    depends_on:
      - mongo-database
