apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actuate
  template:
    metadata:
      labels:
        app: actuate
    spec:
      containers:
      - name: actuate
        image: actuate:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: MQTT_HOST
          value: "mosquitto-cloud"
        - name: MQTT_PORT
          value: "1884"
---
apiVersion: v1
kind: Service
metadata:
  name: actuate
spec:
  selector:
    app: actuate
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
