apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregate
  template:
    metadata:
      labels:
        app: aggregate
    spec:
      containers:
      - name: aggregate
        image: aggregate:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_TOKEN
          value: "secrettoken"
        - name: INFLUXDB_ORG
          value: "UDL"
        - name: INFLUXDB_BUCKET_AGGREGATE
          value: "aggregate_data"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregate
spec:
  selector:
    app: aggregate
  ports:
    - name: http
      protocol: TCP
      port: 5004
      targetPort: 5004
