version: "3.9"
services:
  influxdb:
    image: influxdb:2.4.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=eloi
      - DOCKER_INFLUXDB_INIT_PASSWORD=12341234
      - DOCKER_INFLUXDB_INIT_ORG=UDL
      - DOCKER_INFLUXDB_INIT_BUCKET=measurement
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secrettoken
    volumes:
      - /Users/eloigabal/Desktop/Distributed Computing/2425/examples/docker_data/influxdb:/var/lib/influxdb2
